package com.adminlte.commons.scan;

//用户操作的类型 
public enum Achievetype {
	LOGIN,
	NEWPROJECT,
	UPDATEPROJECT,
	NEWBIDS,
	UPDATEBIDS,
	NEWPROGRESS,
	DELETEPROGRESS,
	NEWMILESTONE,
	DELETEMILESTONE,
	UPDATEMILESTONE,
	NEWDOCUMENT,
	DELETEDOCUMENT,
	NEWMESSAGE,
	DELETEMESSAGE
}
